server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /game {
        return 301 /game/;
    }

    location /game/ {
        try_files $uri $uri/ /game/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}