server {
    listen 80;
    server_name localhost;
    return 301 https://$http_host$request_uri;
}

server {
    listen 443 ssl default_server;
    server_name localhost;

    ssl_certificate /etc/ssl/certs/selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/selfsigned.key;

    # Internal DNS resolver (Podman & Docker fallback)
    resolver 10.89.0.1 127.0.0.11 valid=5s ipv6=off;

    # Frontend (Vite SPA & 3D Assets)
    location / {
        set $upstream_frontend http://ft_frontend:80;
        proxy_pass $upstream_frontend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # NestJS Backend API
    location /api/ {
        set $upstream_backend http://ft_backend:3000;
        proxy_pass $upstream_backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Real-Time WebSocket for Multiplayer Game
    location /ws/ {
        set $upstream_ws http://ft_backend:3000;
        proxy_pass $upstream_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
    }

    # Serveur de jeu
    location /socket.io/ {
        set $upstream_game http://ft_game:3001;
        proxy_pass $upstream_game;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
    }
}
